OIST-CNRU:NRL: oist::LayerPvrnn Class Reference
oist::LayerPvrnn Class Reference
#include <LayerPvrnn.h>
Public Member Functions
LayerPvrnn (int id, int d_num, int d_num_bottom, int d_num_top, int z_num, int z_sum, int tau, int tau_bottom, int tau_top, int prim_num, int prim_len, float w)
~LayerPvrnn ()
int getStateDim ()
void initContext (int)
IContext * getContext ()
void t_generate (int, int)
void t_forward (int, int)
void t_initBackward ()
void t_backward (int, int)
void t_optAdam (int, float, float, float)
void load (string)
void save (string)
void a_init (float *)
void a_predict ()
void a_save (string)
void e_enable (int, int, float, int, bool, bool)
void e_generate ()
void e_initForward ()
void e_forward ()
void e_initBackward ()
void e_backward (int)
void e_copyParam ()
void e_overwriteParam ()
void e_optAdam (int, float, float, float)
float * e_getState (float *)
void e_save (string)
void print ()
Public Member Functions inherited from oist::ILayer
virtual ~ILayer ()
Detailed Description
This class implements a layer type PV-RNN
Definition at line 63 of file LayerPvrnn.h.
Constructor & Destructor Documentation
LayerPvrnn()
oist::LayerPvrnn::LayerPvrnn (int id, int d_num, int d_num_bottom, int d_num_top, int z_num, int z_sum, int tau, int tau_bottom, int tau_top, int prim_num, int prim_len, float w)
Constructor
Parameters
id Layer id
d_num Number Number of d units
d_num_bottom Number of d units (bottom level)
d_num_top Number of d units (top level)
z_num Number of z units
z_sum Sum of z units for all layers in the network
tau Time constant
tau_bottom Time constant (bottom level)
tau_top Time constant (top level)
prim_num Number of primitives
prim_len Length of primitives
w Meta-parameter w
Definition at line 54 of file LayerPvrnn.cpp.
References oist::ContextPvrnn::dp_bottom_prev, oist::ContextPvrnn::dp_top_prev, oist::ContextPvrnn::dq_bottom_prev, oist::ContextPvrnn::dq_top_prev, oist::ContextPvrnn::g_dqloss, oist::ContextPvrnn::g_h_next, oist::ContextPvrnn::g_hq_bottom_next, oist::ContextPvrnn::g_hq_top_next, oist::Utils::getInstance(), oist::Utils::kaiming_uniform_initialization(), oist::ContextPvrnn::t_dp, oist::ContextPvrnn::t_dq, and oist::ContextPvrnn::t_kld.
~LayerPvrnn()
oist::LayerPvrnn::~LayerPvrnn ()
Destructor
Definition at line 1781 of file LayerPvrnn.cpp.
Member Function Documentation
a_init()
void oist::LayerPvrnn::a_init (float *) virtual
[Analysis mode] Initialize off-line predictions
Parameters
Input state at time t=0
Implements oist::ILayer.
Definition at line 1667 of file LayerPvrnn.cpp.
References oist::ContextPvrnn::dp_gen.
a_predict()
void oist::LayerPvrnn::a_predict () virtual
[Analysis mode] Computes the generative process off-line
Implements oist::ILayer.
Definition at line 1688 of file LayerPvrnn.cpp.
References oist::ContextPvrnn::dp_bottom_prev, oist::ContextPvrnn::dp_gen, oist::ContextPvrnn::dp_top_prev, oist::Utils::randN(), and oist::Utils::tanH().
a_save()
void oist::LayerPvrnn::a_save (string path) virtual
[Analysis mode] Save off-line computations to disk
Parameters
path Directory full path
Implements oist::ILayer.
Definition at line 1723 of file LayerPvrnn.cpp.
References oist::Utils::getDelimiter(), and oist::Utils::saveEigen().
e_backward()
void oist::LayerPvrnn::e_backward (int time) virtual
[Experiment mode] Computes the backward pass of the BPTT algorithm for performing inference
Parameters
time Current time step
Implements oist::ILayer.
Definition at line 1303 of file LayerPvrnn.cpp.
References oist::ContextPvrnn::g_dqloss, oist::ContextPvrnn::g_h_next, oist::ContextPvrnn::g_hq_bottom_next, oist::ContextPvrnn::g_hq_top_next, and NON_ZERO.
e_copyParam()
void oist::LayerPvrnn::e_copyParam () virtual
[Experiment model] Copies the parameters with optimal loss function (greedy optimization)
Implements oist::ILayer.
Definition at line 1435 of file LayerPvrnn.cpp.
References oist::ContextPvrnn::dp_gen, and oist::ContextPvrnn::e_dq.
e_enable()
void oist::LayerPvrnn::e_enable (int pID, int winSize, float param, int nT, bool store_gen, bool store_inf) virtual
[Experiment mode] Enables the experiment mode
Parameters
pID Primitive ID
winSize Sliding window size
param Input container with parameters
nT Number of experiment times
store_gen A flag indicating to store the generative process states. This should be used with caution, since memory allocation for large data may degrade performance. It is recommended to use e_getState to get the current state of the network, without storing information on the back-end side. Hence, the client front-end does the storage.
store_inf A flag indicating to store the inference process states. Valuable only if the parameter store_gen is set true. Thus should be used only for debugging, since memory allocation for large data may degrade performance. All the computation steps for the back propagation trough time (BPPT) algorithm are stored.
Implements oist::ILayer.
Definition at line 1030 of file LayerPvrnn.cpp.
References oist::ContextPvrnn::dp_bottom_prev, oist::ContextPvrnn::dp_gen, oist::ContextPvrnn::dp_top_prev, oist::ContextPvrnn::dq_bottom_prev, and oist::ContextPvrnn::dq_top_prev.
e_forward()
void oist::LayerPvrnn::e_forward () virtual
[Experiment mode] Computes forward inference process
Implements oist::ILayer.
Definition at line 1235 of file LayerPvrnn.cpp.
References oist::ContextPvrnn::dp_bottom_prev, oist::ContextPvrnn::dp_top_prev, oist::ContextPvrnn::dq_bottom_prev, oist::ContextPvrnn::dq_top_prev, oist::ContextPvrnn::e_dp, oist::ContextPvrnn::e_dq, oist::ContextPvrnn::e_kld, oist::Utils::randN(), and oist::Utils::tanH().
e_generate()
void oist::LayerPvrnn::e_generate () virtual
[Experiment mode] Computes one prediction with the generative process
Implements oist::ILayer.
Definition at line 1180 of file LayerPvrnn.cpp.
References oist::ContextPvrnn::dp_bottom_prev, oist::ContextPvrnn::dp_gen, oist::ContextPvrnn::dp_top_prev, oist::Utils::randN(), and oist::Utils::tanH().
e_getState()
float * oist::LayerPvrnn::e_getState (float * output) virtual
[Experiment mode] Writes the current layer state to a float array. Both the generation and inference latent states are provided real time for analysis.
Parameters
output Float array reference. The size of the array can be obtained from getStateDim
Returns
Pointer to the next writable position in the float array
Implements oist::ILayer.
Definition at line 1475 of file LayerPvrnn.cpp.
References oist::Utils::copyEigenData(), oist::ContextPvrnn::dp_gen, oist::ContextPvrnn::e_dp, and oist::ContextPvrnn::e_dq.
e_initBackward()
void oist::LayerPvrnn::e_initBackward () virtual
[Experiment mode] Initializes the backward inference process computation
Implements oist::ILayer.
Definition at line 1159 of file LayerPvrnn.cpp.
References oist::ContextPvrnn::e_dq, and t_initBackward().
e_initForward()
void oist::LayerPvrnn::e_initForward () virtual
[Experiment mode] Initialize the inference process forward computations
Implements oist::ILayer.
Definition at line 1112 of file LayerPvrnn.cpp.
References oist::ContextPvrnn::e_dp, oist::ContextPvrnn::e_dq, and oist::ContextPvrnn::e_kld.
e_optAdam()
void oist::LayerPvrnn::e_optAdam (int pID, float alpha, float beta1, float beta2) virtual
[Experiment mode] Computes ADAM optimization of parameters
Parameters
pID Primitive ID
alpha Adam optimization hyper parameter
beta1 Adam optimization hyper parameter
beta2 Adam optimization hyper parameter
Implements oist::ILayer.
Definition at line 1366 of file LayerPvrnn.cpp.
References oist::Utils::adam(), oist::ContextPvrnn::e_dp, oist::ContextPvrnn::e_dq, oist::ContextPvrnn::e_kld, and oist::Utils::zero().
e_overwriteParam()
void oist::LayerPvrnn::e_overwriteParam () virtual
[Experiment model] Persists the parameters with optimal loss function (greedy optimization)
Implements oist::ILayer.
Definition at line 1453 of file LayerPvrnn.cpp.
References oist::Utils::zero().
e_save()
void oist::LayerPvrnn::e_save (string path) virtual
[Experiment mode] Save the network model
Parameters
path Output directory full path
Implements oist::ILayer.
Definition at line 1518 of file LayerPvrnn.cpp.
References oist::Utils::getDelimiter(), oist::Utils::saveEigen(), and oist::Utils::saveScalar().
getContext()
IContext * oist::LayerPvrnn::getContext () virtual
Gets the layer context
Implements oist::ILayer.
Definition at line 256 of file LayerPvrnn.cpp.
getStateDim()
int oist::LayerPvrnn::getStateDim () virtual
Gets the dimension of the layer state space
Returns
dimension
Implements oist::ILayer.
Definition at line 252 of file LayerPvrnn.cpp.
initContext()
void oist::LayerPvrnn::initContext (int pID) virtual
Initialized the layer context
Parameters
pID Primitive ID
Implements oist::ILayer.
Definition at line 260 of file LayerPvrnn.cpp.
References oist::ContextPvrnn::t_dp, oist::ContextPvrnn::t_dq, and oist::ContextPvrnn::t_kld.
load()
void oist::LayerPvrnn::load (string path) virtual
Load the layer's parameters
Parameters
path path Data full path
Implements oist::ILayer.
Definition at line 695 of file LayerPvrnn.cpp.
References oist::Utils::getDelimiter(), oist::Utils::loadEigen(), and oist::Exception::what().
print()
void oist::LayerPvrnn::print () virtual
Shows the network state in the standard output
Implements oist::ILayer.
Definition at line 598 of file LayerPvrnn.cpp.
save()
void oist::LayerPvrnn::save (string path) virtual
Save the layer's parameters
Parameters
path Destination full path
Implements oist::ILayer.
Definition at line 826 of file LayerPvrnn.cpp.
References oist::Utils::getDelimiter(), oist::Utils::saveEigen(), and oist::Exception::what().
t_backward()
void oist::LayerPvrnn::t_backward (int time, int pID) virtual
[Training mode] Computes the backward (BPTT algorithm) inference process
Parameters
time Current time step
pID Primitive ID
Implements oist::ILayer.
Definition at line 440 of file LayerPvrnn.cpp.
References oist::ContextPvrnn::dq_bottom_prev, oist::ContextPvrnn::dq_top_prev, oist::ContextPvrnn::g_dqloss, oist::ContextPvrnn::g_h_next, oist::ContextPvrnn::g_hq_bottom_next, oist::ContextPvrnn::g_hq_top_next, NON_ZERO, oist::ContextPvrnn::t_dp, and oist::ContextPvrnn::t_dq.
t_forward()
void oist::LayerPvrnn::t_forward (int time, int pID) virtual
[Training mode] Computes the forward inference process
Parameters
time Current time step
pID Primitive ID
Implements oist::ILayer.
Definition at line 359 of file LayerPvrnn.cpp.
References oist::ContextPvrnn::dp_bottom_prev, oist::ContextPvrnn::dp_top_prev, oist::ContextPvrnn::dq_bottom_prev, oist::ContextPvrnn::dq_top_prev, oist::Utils::randN(), oist::ContextPvrnn::t_dp, oist::ContextPvrnn::t_dq, oist::ContextPvrnn::t_kld, and oist::Utils::tanH().
t_generate()
void oist::LayerPvrnn::t_generate (int time, int pID) virtual
[Training mode] Computes the generative process
Parameters
time Current time step
pID Primitive ID
Implements oist::ILayer.
Definition at line 302 of file LayerPvrnn.cpp.
References oist::ContextPvrnn::dp_bottom_prev, oist::ContextPvrnn::dp_top_prev, oist::Utils::randN(), oist::ContextPvrnn::t_dp, and oist::Utils::tanH().
t_initBackward()
void oist::LayerPvrnn::t_initBackward () virtual
[Training mode] Initializes the inference process backward computation
Implements oist::ILayer.
Definition at line 430 of file LayerPvrnn.cpp.
References oist::ContextPvrnn::g_h_next, and oist::Utils::zero().
Referenced by e_initBackward().
t_optAdam()
void oist::LayerPvrnn::t_optAdam (int pID, float alpha, float beta1, float beta2) virtual
[Training mode] Computes ADAM optimization of parameters
Parameters
pID Primitive ID
alpha Adam optimization hyper parameter
beta1 Adam optimization hyper parameter
beta2 Adam optimization hyper parameter
Implements oist::ILayer.
Definition at line 533 of file LayerPvrnn.cpp.
References oist::Utils::adam(), and oist::Utils::zero().
The documentation for this class was generated from the following files:
src/layer/LayerPvrnn.h
src/layer/LayerPvrnn.cpp