OIST-CNRU:NRL: oist::INetwork Class Reference
oist::INetwork Class Reference abstract
#include <INetwork.h>
Public Member Functions
virtual int getNLayers ()=0
virtual int getStateDim ()=0
virtual void load (string path)=0
virtual void save (string path)=0
virtual float getRecError (vectorXf2DContainer &gen, vectorXf3DContainer &ref)=0
virtual void t_generate (int n, int pID, vectorXf2DContainer &output)=0
virtual void t_forward (int n, int pID, vectorXf2DContainer &output)=0
virtual void t_backward (int epoch, vectorXf2DContainer &X, vectorXf3DContainer &Y, float &rec, float &reg, float &loss)=0
virtual void t_optAdam (int pID, float alpha, float beta1, float beta2)=0
virtual void a_predict (int n, float *input, string path)=0
virtual void a_feedForwardOutputFromContext (float *input, float *output)=0
virtual void e_enable (int pID, int winSize, float *param, int nT, bool store_gen, bool store_inf)=0
virtual void e_generate (float *output)=0
virtual bool e_initForward ()=0
virtual void e_forward (vectorXf2DContainer &output)=0
virtual void e_backward (vectorXf2DContainer &X, vectorXf2DContainer &Y, float &rec, float &reg, float &loss)=0
virtual void e_copyParam ()=0
virtual void e_overwriteParam ()=0
virtual void e_optAdam (int pID, float alpha, float beta1, float beta2)=0
virtual void e_getState (float *output)=0
virtual void e_save (string path)=0
virtual ~INetwork ()
Detailed Description
Abstract class (Interface) for network implementations
Definition at line 59 of file INetwork.h.
Constructor & Destructor Documentation
~INetwork()
virtual oist::INetwork::~INetwork () inline virtual
Destructor
Definition at line 236 of file INetwork.h.
Member Function Documentation
a_feedForwardOutputFromContext()
virtual void oist::INetwork::a_feedForwardOutputFromContext (float * input, float * output) pure virtual
[Analysis mode] Computes the output from feed-forwarding a given context. This method does not modify the internal state of the network, (i.e. the generative and inference processes are not involved). It only computes the output layer from a given context.
Parameters
input Input array with latent state for the involved layers concatenated
output Output container
Implemented in oist::NetworkPvrnnBeta, and oist::NetworkPvrnn.
Referenced by oist::LibNRL::a_feedForwardOutputFromContext().
a_predict()
virtual void oist::INetwork::a_predict (int n, float * input, string path) pure virtual
[Analysis mode] Computes the generative process off-line and stores on disk
Parameters
n Number of generations
input Input array with initial state for all the layers concatenated
path Full path directory to save the output
Implemented in oist::NetworkPvrnnBeta, and oist::NetworkPvrnn.
Referenced by oist::LibNRL::a_predict().
e_backward()
virtual void oist::INetwork::e_backward (vectorXf2DContainer & X, vectorXf2DContainer & Y, float & rec, float & reg, float & loss) pure virtual
[Experiment mode] Back propagation through time computation (inference)
Parameters
X Input container with network generation from the posterior distribution e_forward
Y Input container with the reference data
rec Output reconstruction error
reg Output regulation error
loss Output loss function
Implemented in oist::NetworkPvrnnBeta, and oist::NetworkPvrnn.
Referenced by oist::LibNRL::e_postdict().
e_copyParam()
virtual void oist::INetwork::e_copyParam () pure virtual
[Experiment mode] Copies the network's parameters. It is used for greedy optimization
Implemented in oist::NetworkPvrnnBeta, and oist::NetworkPvrnn.
Referenced by oist::LibNRL::e_postdict().
e_enable()
virtual void oist::INetwork::e_enable (int pID, int winSize, float * param, int nT, bool store_gen, bool store_inf) pure virtual
[Experiment mode] Enables the experiment mode
Parameters
pID Primitive ID
winSize Sliding window size
param container with parameters
nT Number of experiment times
store_gen A flag indicating to store the generative process states. This should be used with caution, since memory allocation for large data may degrade performance. It is recommended to use e_getState to get the current state of the network, without storing information on the back-end side. Hence, the client front-end does the storage.
store_inf A flag indicating to store the inference process states. Valuable only if the parameter store_gen is set true. Thus should be used only for debugging, since memory allocation for large data may degrade performance. All the computation steps for the back propagation trough time (BPPT) algorithm are stored.
Implemented in oist::NetworkPvrnnBeta, and oist::NetworkPvrnn.
Referenced by oist::LibNRL::e_enable().
e_forward()
virtual void oist::INetwork::e_forward (vectorXf2DContainer & output) pure virtual
[Experiment mode] Generation from the posterior distribution
Parameters
output Container for output recording
Implemented in oist::NetworkPvrnnBeta, and oist::NetworkPvrnn.
Referenced by oist::LibNRL::e_postdict().
e_generate()
virtual void oist::INetwork::e_generate (float * output) pure virtual
[Experiment mode] Generation from the prior distribution
Parameters
output Container for output recording
Implemented in oist::NetworkPvrnnBeta, and oist::NetworkPvrnn.
Referenced by oist::LibNRL::e_generate().
e_getState()
virtual void oist::INetwork::e_getState (float * output) pure virtual
[Experiment mode] Writes the current network state to a float array. Both the generation and inference latent states are provided real time for analysis.
Parameters
output Float array reference. The size of the array can be obtained from getStateDim
Implemented in oist::NetworkPvrnnBeta, and oist::NetworkPvrnn.
Referenced by oist::LibNRL::e_getState().
e_initForward()
virtual bool oist::INetwork::e_initForward () pure virtual
[Experiment mode] Initialize the inference process forward computations in experiment mode
Returns
A flag indicating the success of the operation
Implemented in oist::NetworkPvrnnBeta, and oist::NetworkPvrnn.
Referenced by oist::LibNRL::e_postdict().
e_optAdam()
virtual void oist::INetwork::e_optAdam (int pID, float alpha, float beta1, float beta2) pure virtual
[Experiment mode] Computes ADAM optimization of parameters
Parameters
pID Primitive ID
alpha Adam optimization hyper parameter
beta1 Adam optimization hyper parameter
beta2 Adam optimization hyper parameter
Implemented in oist::NetworkPvrnnBeta, and oist::NetworkPvrnn.
Referenced by oist::LibNRL::e_postdict().
e_overwriteParam()
virtual void oist::INetwork::e_overwriteParam () pure virtual
[Experiment mode] Overrides the network's parameters. It is used for greedy optimization
Implemented in oist::NetworkPvrnnBeta, and oist::NetworkPvrnn.
Referenced by oist::LibNRL::e_postdict().
e_save()
virtual void oist::INetwork::e_save (string path) pure virtual
[Experiment mode] Save the network model
Parameters
path Output directory full path
Implemented in oist::NetworkPvrnnBeta, and oist::NetworkPvrnn.
Referenced by oist::LibNRL::e_save().
getNLayers()
virtual int oist::INetwork::getNLayers () pure virtual
Get the number of layers
Returns
An integer representing the number of layers
Implemented in oist::NetworkPvrnnBeta, and oist::NetworkPvrnn.
Referenced by oist::LibNRL::getNLayers().
getRecError()
virtual float oist::INetwork::getRecError (vectorXf2DContainer & gen, vectorXf3DContainer & ref) pure virtual
Get the reconstruction error
Parameters
gen Container with the output generation by network
ref Container with the reference data
Returns
A real value for the reconstruction error
Implemented in oist::NetworkPvrnnBeta, and oist::NetworkPvrnn.
Referenced by oist::LibNRL::t_background(), and oist::LibNRL::t_loop().
getStateDim()
virtual int oist::INetwork::getStateDim () pure virtual
Gets the dimension of the network state space
Returns
An integer representing the dimension
Implemented in oist::NetworkPvrnnBeta, and oist::NetworkPvrnn.
Referenced by oist::LibNRL::getStateDim().
load()
virtual void oist::INetwork::load (string path) pure virtual
Load the network model
Parameters
path Model directory full path
Implemented in oist::NetworkPvrnnBeta, and oist::NetworkPvrnn.
Referenced by oist::LibNRL::load(), oist::LibNRL::t_background(), and oist::LibNRL::t_init().
save()
virtual void oist::INetwork::save (string path) pure virtual
Save the network model
Parameters
path Model directory full path
Implemented in oist::NetworkPvrnnBeta, and oist::NetworkPvrnn.
Referenced by oist::LibNRL::t_background(), and oist::LibNRL::t_loop().
t_backward()
virtual void oist::INetwork::t_backward (int epoch, vectorXf2DContainer & X, vectorXf3DContainer & Y, float & rec, float & reg, float & loss) pure virtual
[Training mode] Back propagation through time computation (inference)
Parameters
epoch current epoch number
X Input container with network generation from the posterior distribution t_forward
Y Input container with the reference data
rec Output reconstruction error
reg Output regulation error
loss Output loss function
Implemented in oist::NetworkPvrnnBeta, and oist::NetworkPvrnn.
Referenced by oist::LibNRL::t_background(), and oist::LibNRL::t_loop().
t_forward()
virtual void oist::INetwork::t_forward (int n, int pID, vectorXf2DContainer & output) pure virtual
[Training mode] Generation from the posterior distribution
Parameters
n number of time steps
pID Primitive ID
output Container for output recording
Implemented in oist::NetworkPvrnnBeta, and oist::NetworkPvrnn.
Referenced by oist::LibNRL::t_background(), and oist::LibNRL::t_loop().
t_generate()
virtual void oist::INetwork::t_generate (int n, int pID, vectorXf2DContainer & output) pure virtual
[Training mode] Generation from the prior distribution
Parameters
n number of time steps
pID Primitive ID
output Container for output recording
Implemented in oist::NetworkPvrnnBeta, and oist::NetworkPvrnn.
Referenced by oist::LibNRL::t_background(), and oist::LibNRL::t_loop().
t_optAdam()
virtual void oist::INetwork::t_optAdam (int pID, float alpha, float beta1, float beta2) pure virtual
[Training mode] Computes ADAM optimization of parameters
Parameters
pID Primitive ID
alpha Adam optimization hyper parameter
beta1 Adam optimization hyper parameter
beta2 Adam optimization hyper parameter
Implemented in oist::NetworkPvrnnBeta, and oist::NetworkPvrnn.
Referenced by oist::LibNRL::t_background(), and oist::LibNRL::t_loop().
The documentation for this class was generated from the following file:
src/network/INetwork.h