OIST-CNRU:NRL: oist::LibNRL Class Reference
oist::LibNRL Class Reference
#include <LibNRL.h>
Public Member Functions
void newModel (string path)
int getNDof ()
int getNLayers ()
int getStateDim ()
void load ()
void t_init (bool show)
void t_loop (float *output, int n)
void t_end ()
void t_background ()
void e_enable (int pID, int ws, float *param, int ne, int epoch, float alpha, float beta1, float beta2, bool store_s, bool store_p)
void e_postdict (float *input, float *output, bool show)
void e_generate (float *output)
void e_save (string path)
void e_getState (float *output)
void a_predict (const char *path, int n, float *input)
void a_feedForwardOutputFromContext (float *input, float *output)
Static Public Member Functions
static LibNRL * getInstance ()
Detailed Description
This class provides the NRL functionalities for training a neural network model, performing on-line experiments, and computing off-line analysis. For this, the class considers the parameters provided in a properties file to the method newModel. The description of the parameters can be found in the document section Backend parametrization The class implements a singleton design pattern.
Definition at line 76 of file LibNRL.h.
Member Function Documentation
void oist::LibNRL::a_feedForwardOutputFromContext (float * input, float * output)
Computes the output from feed-forwarding a given context. This method does not modify the internal state of the network, (i.e. the generative and inference processes are not involved). It only computes the output layer from a given context.
Parameters
input Array with latent state, whose dimension can be obtained through 'getStateDim'
output Array container
Definition at line 728 of file LibNRL.cpp.
References oist::INetwork::a_feedForwardOutputFromContext().
Referenced by a_getOutputFromContext().
void oist::LibNRL::a_predict (const char * path, int n, float * input)
Generative off-line n time steps predictions from the initial context provided and store computations on disk.
Parameters
path Output full path dir
n Number of time steps
input Array with latent state, whose dimension can be obtained through 'getStateDim'
Definition at line 716 of file LibNRL.cpp.
References oist::INetwork::a_predict().
Referenced by a_predict().
void oist::LibNRL::e_enable (int pID, int ws, float * param, int ne, int epoch, float alpha, float beta1, float beta2, bool store_s, bool store_p)
Enables on-line experiment mode
Parameters
pID Primitive ID
ws Sliding window size
param Parameters array for the neural network model
ne Number of experiment time steps
epoch Number of post-diction epochs
alpha Adam optimization hyper parameter
beta1 Adam optimization hyper parameter
beta2 Adam optimization hyper parameter
store_s A flag indicating to store the states on disk (if true performance can be affected)
store_p A flag indicating to store intermediate BPPT computations (if true performance can be affected)
Definition at line 603 of file LibNRL.cpp.
References oist::INetwork::e_enable().
Referenced by demonstrateExperiment(), and e_enable().
void oist::LibNRL::e_generate (float * output)
Generates output from the prior distribution
Parameters
output Array for storing the robot joint positions
Definition at line 676 of file LibNRL.cpp.
References oist::INetwork::e_generate().
Referenced by demonstrateExperiment(), and e_generate().
void oist::LibNRL::e_getState (float * output)
Gets the current state of the network and writes data to the output buffer. This method is recommended for saving data in experiments.
Parameters
output Array with latent state, whose dimension can be obtained through getStateDim once the model has been loaded.
Definition at line 701 of file LibNRL.cpp.
References oist::INetwork::e_getState().
Referenced by demonstrateExperiment(), and e_getState().
void oist::LibNRL::e_postdict (float * input, float * output, bool show)
Computes the post-diction (inference) process
Parameters
input Sliding window buffer array
output Array for loss function components (reconstruction error, regulation error, loss)
show A flag indicating to show log in the standard output
Definition at line 629 of file LibNRL.cpp.
References oist::INetwork::e_backward(), oist::INetwork::e_copyParam(), oist::INetwork::e_forward(), oist::INetwork::e_initForward(), oist::INetwork::e_optAdam(), oist::INetwork::e_overwriteParam(), and oist::Dataset::encodeSoftmax().
Referenced by demonstrateExperiment(), and e_postdict().
void oist::LibNRL::e_save (string path)
Stores the experimental data in disk in case this functionality was set in e_enable It is recommended saving data in background only for short-time experiments, since performance can be affected. Another way of storing information is through the method e_getState which do not buffer data history but provides only the current state. Hence, the client application is in charge of storing data locally.
Parameters
path Output full path
Definition at line 688 of file LibNRL.cpp.
References oist::INetwork::e_save().
Referenced by e_save().
LibNRL * oist::LibNRL::getInstance () static
Definition at line 58 of file LibNRL.cpp.
References oist::Utils::getInstance().
Referenced by getInstance().
int oist::LibNRL::getNDof ()
Gets the number of degrees of freedom (DoF) of the network output
Returns
Number of DoF
Definition at line 249 of file LibNRL.cpp.
Referenced by demonstrateExperiment(), and getNDof().
int oist::LibNRL::getNLayers ()
Gets the number of intermediate layers
Returns
Number of layers
Definition at line 261 of file LibNRL.cpp.
References oist::INetwork::getNLayers().
Referenced by getNLayers().
int oist::LibNRL::getStateDim ()
Gets the dimension of the network state space
Returns
Dimension
Definition at line 273 of file LibNRL.cpp.
References oist::INetwork::getStateDim().
Referenced by demonstrateExperiment(), and getStateDim().
void oist::LibNRL::load ()
Loads the network model
Definition at line 285 of file LibNRL.cpp.
References oist::INetwork::load(), and oist::Exception::what().
Referenced by demonstrateExperiment(), and load().
void oist::LibNRL::newModel (string path)
Creates a new model
Parameters
path Property file full path
Definition at line 111 of file LibNRL.cpp.
References oist::Utils::getDelimiter(), oist::IRobot::getDOF(), oist::Torobo::getInstance(), oist::Cartesian::getInstance(), oist::Generic::getInstance(), oist::Utils::getProperties(), oist::Utils::loadContainer(), and oist::Exception::what().
Referenced by main(), and newModel().
void oist::LibNRL::t_background ()
Training in background mode. The training parameters are fully red from the properties file
Definition at line 455 of file LibNRL.cpp.
References oist::Utils::getDelimiter(), oist::INetwork::getRecError(), oist::INetwork::load(), oist::Utils::loadContainer(), oist::INetwork::save(), oist::Utils::shuffle(), oist::INetwork::t_backward(), oist::INetwork::t_forward(), oist::INetwork::t_generate(), oist::INetwork::t_optAdam(), and oist::Exception::what().
Referenced by demonstrateTraining(), and t_background().
void oist::LibNRL::t_end ()
Ending of interactive training mode
Definition at line 443 of file LibNRL.cpp.
Referenced by t_end().
void oist::LibNRL::t_init (bool show)
Initialization of interactive training mode
Parameters
show Flag indicating to log training in the stdout
Definition at line 300 of file LibNRL.cpp.
References oist::Utils::getDelimiter(), oist::INetwork::load(), oist::Utils::loadContainer(), and oist::Exception::what().
Referenced by t_init().
void oist::LibNRL::t_loop (float * output, int n)
Loop iteration in interactive training mode
Parameters
output Output array for the tuple (step, RE_Q, RE_P, REG, loss, opt)
Field Description
step Current training time step
RE_Q Reconstruction error from the posterior distribution
RE_P Reconstruction error from the prior distribution
REG Regulation error KL-Div(Prior,posterior)
loss Loss function error
opt Integer flag: (1) Global optimal loss, (0) otherwise
n Number of training epochs
Definition at line 347 of file LibNRL.cpp.
References oist::INetwork::getRecError(), oist::INetwork::save(), oist::Utils::shuffle(), oist::INetwork::t_backward(), oist::INetwork::t_forward(), oist::INetwork::t_generate(), and oist::INetwork::t_optAdam().
Referenced by t_loop().
The documentation for this class was generated from the following files:
src/lib/LibNRL.h
src/lib/LibNRL.cpp