OIST-CNRU:NRL: oist::LayerPvrnnBeta Class Reference
oist::LayerPvrnnBeta Class Reference
#include <LayerPvrnnBeta.h>
Public Member Functions
LayerPvrnnBeta (int id, int d_num, int d_num_top, int z_num, int z_sum, int tau, int tau_top, int prim_num, int prim_len, float w1, float w)
~LayerPvrnnBeta ()
int getStateDim ()
void initContext (int)
IContext * getContext ()
void t_generate (int, int)
void t_forward (int, int)
void t_initBackward ()
void t_backward (int, int)
void t_optAdam (int, float, float, float)
void load (string)
void save (string)
void a_init (float *)
void a_predict ()
void a_save (string)
void e_enable (int, int, float, int, bool, bool)
void e_generate ()
void e_initForward ()
void e_forward ()
void e_initBackward ()
void e_backward (int)
void e_copyParam ()
void e_overwriteParam ()
void e_optAdam (int, float, float, float)
float * e_getState (float *)
void e_save (string)
void print ()
Public Member Functions inherited from oist::ILayer
virtual ~ILayer ()
Detailed Description
This class implements a layer type PV-RNN
Definition at line 63 of file LayerPvrnnBeta.h.
Constructor & Destructor Documentation
LayerPvrnnBeta()
oist::LayerPvrnnBeta::LayerPvrnnBeta (int id, int d_num, int d_num_top, int z_num, int z_sum, int tau, int tau_top, int prim_num, int prim_len, float w1, float w)
Constructor
Parameters
id Layer id
d_num Number Number of d units
d_num_top Number of d units (top level)
z_num Number of z units
z_sum Sum of z units for all layers in the network
tau Time constant
tau_top Time constant (top level)
prim_num Number of primitives
prim_len Length of primitives
w1 Meta-parameter w (t=1)
w Meta-parameter w
Definition at line 54 of file LayerPvrnnBeta.cpp.
References oist::ContextPvrnnBeta::dp_top, oist::ContextPvrnnBeta::dq_top, oist::ContextPvrnnBeta::g_dqloss, oist::ContextPvrnnBeta::g_h_next, oist::ContextPvrnnBeta::g_hq_top, oist::Utils::getInstance(), oist::Utils::kaiming_uniform_initialization(), oist::ContextPvrnnBeta::t_dp, oist::ContextPvrnnBeta::t_dq, and oist::ContextPvrnnBeta::t_kld.
~LayerPvrnnBeta()
oist::LayerPvrnnBeta::~LayerPvrnnBeta ()
Destructor
Definition at line 1747 of file LayerPvrnnBeta.cpp.
Member Function Documentation
a_init()
void oist::LayerPvrnnBeta::a_init (float *) virtual
[Analysis mode] Initialize off-line predictions
Parameters
Input state at time t=0
Implements oist::ILayer.
Definition at line 1635 of file LayerPvrnnBeta.cpp.
References oist::ContextPvrnnBeta::dp_gen.
a_predict()
void oist::LayerPvrnnBeta::a_predict () virtual
[Analysis mode] Computes the generative process off-line
Implements oist::ILayer.
Definition at line 1656 of file LayerPvrnnBeta.cpp.
References oist::ContextPvrnnBeta::dp_gen, oist::ContextPvrnnBeta::dp_top, oist::Utils::randN(), and oist::Utils::tanH().
a_save()
void oist::LayerPvrnnBeta::a_save (string path) virtual
[Analysis mode] Save off-line computations to disk
Parameters
path Directory full path
Implements oist::ILayer.
Definition at line 1689 of file LayerPvrnnBeta.cpp.
References oist::Utils::getDelimiter(), and oist::Utils::saveEigen().
e_backward()
void oist::LayerPvrnnBeta::e_backward (int time) virtual
[Experiment mode] Computes the backward pass of the BPTT algorithm for performing inference
Parameters
time Current time step
Implements oist::ILayer.
Definition at line 1273 of file LayerPvrnnBeta.cpp.
References oist::ContextPvrnnBeta::g_dqloss, oist::ContextPvrnnBeta::g_h_next, oist::ContextPvrnnBeta::g_hq_top, and NON_ZERO.
e_copyParam()
void oist::LayerPvrnnBeta::e_copyParam () virtual
[Experiment model] Copies the parameters with optimal loss function (greedy optimization)
Implements oist::ILayer.
Definition at line 1403 of file LayerPvrnnBeta.cpp.
References oist::ContextPvrnnBeta::dp_gen, and oist::ContextPvrnnBeta::e_dq.
e_enable()
void oist::LayerPvrnnBeta::e_enable (int pID, int winSize, float param, int nT, bool store_gen, bool store_inf) virtual
[Experiment mode] Enables the experiment mode
Parameters
pID Primitive ID
winSize Sliding window size
param Input container with parameters
nT Number of experiment times
store_gen A flag indicating to store the generative process states. This should be used with caution, since memory allocation for large data may degrade performance. It is recommended to use e_getState to get the current state of the network, without storing information on the back-end side. Hence, the client front-end does the storage.
store_inf A flag indicating to store the inference process states. Valuable only if the parameter store_gen is set true. Thus should be used only for debugging, since memory allocation for large data may degrade performance. All the computation steps for the back propagation trough time (BPPT) algorithm are stored.
Implements oist::ILayer.
Definition at line 1010 of file LayerPvrnnBeta.cpp.
References oist::ContextPvrnnBeta::dp_gen, oist::ContextPvrnnBeta::dp_top, and oist::ContextPvrnnBeta::dq_top.
e_forward()
void oist::LayerPvrnnBeta::e_forward () virtual
[Experiment mode] Computes forward inference process
Implements oist::ILayer.
Definition at line 1209 of file LayerPvrnnBeta.cpp.
References oist::ContextPvrnnBeta::dp_top, oist::ContextPvrnnBeta::dq_top, oist::ContextPvrnnBeta::e_dp, oist::ContextPvrnnBeta::e_dq, oist::ContextPvrnnBeta::e_kld, oist::Utils::randN(), and oist::Utils::tanH().
e_generate()
void oist::LayerPvrnnBeta::e_generate () virtual
[Experiment mode] Computes one prediction with the generative process
Implements oist::ILayer.
Definition at line 1156 of file LayerPvrnnBeta.cpp.
References oist::ContextPvrnnBeta::dp_gen, oist::ContextPvrnnBeta::dp_top, oist::Utils::randN(), and oist::Utils::tanH().
e_getState()
float * oist::LayerPvrnnBeta::e_getState (float * output) virtual
[Experiment mode] Writes the current layer state to a float array. Both the generation and inference latent states are provided real time for analysis.
Parameters
output Float array reference. The size of the array can be obtained from getStateDim
Returns
Pointer to the next writable position in the float array
Implements oist::ILayer.
Definition at line 1443 of file LayerPvrnnBeta.cpp.
References oist::Utils::copyEigenData(), oist::ContextPvrnnBeta::dp_gen, oist::ContextPvrnnBeta::e_dp, and oist::ContextPvrnnBeta::e_dq.
e_initBackward()
void oist::LayerPvrnnBeta::e_initBackward () virtual
[Experiment mode] Initializes the backward inference process computation
Implements oist::ILayer.
Definition at line 1135 of file LayerPvrnnBeta.cpp.
References oist::ContextPvrnnBeta::e_dq, and t_initBackward().
e_initForward()
void oist::LayerPvrnnBeta::e_initForward () virtual
[Experiment mode] Initialize the inference process forward computations
Implements oist::ILayer.
Definition at line 1088 of file LayerPvrnnBeta.cpp.
References oist::ContextPvrnnBeta::e_dp, oist::ContextPvrnnBeta::e_dq, and oist::ContextPvrnnBeta::e_kld.
e_optAdam()
void oist::LayerPvrnnBeta::e_optAdam (int pID, float alpha, float beta1, float beta2) virtual
[Experiment mode] Computes ADAM optimization of parameters
Parameters
pID Primitive ID
alpha Adam optimization hyper parameter
beta1 Adam optimization hyper parameter
beta2 Adam optimization hyper parameter
Implements oist::ILayer.
Definition at line 1334 of file LayerPvrnnBeta.cpp.
References oist::Utils::adam(), oist::ContextPvrnnBeta::e_dp, oist::ContextPvrnnBeta::e_dq, oist::ContextPvrnnBeta::e_kld, and oist::Utils::zero().
e_overwriteParam()
void oist::LayerPvrnnBeta::e_overwriteParam () virtual
[Experiment model] Persists the parameters with optimal loss function (greedy optimization)
Implements oist::ILayer.
Definition at line 1421 of file LayerPvrnnBeta.cpp.
References oist::Utils::zero().
e_save()
void oist::LayerPvrnnBeta::e_save (string path) virtual
[Experiment mode] Save the network model
Parameters
path Output directory full path
Implements oist::ILayer.
Definition at line 1486 of file LayerPvrnnBeta.cpp.
References oist::Utils::getDelimiter(), oist::Utils::saveEigen(), and oist::Utils::saveScalar().
getContext()
IContext * oist::LayerPvrnnBeta::getContext () virtual
Gets the layer context
Implements oist::ILayer.
Definition at line 244 of file LayerPvrnnBeta.cpp.
getStateDim()
int oist::LayerPvrnnBeta::getStateDim () virtual
Gets the dimension of the layer state space
Returns
dimension
Implements oist::ILayer.
Definition at line 240 of file LayerPvrnnBeta.cpp.
initContext()
void oist::LayerPvrnnBeta::initContext (int pID) virtual
Initialized the layer context
Parameters
pID Primitive ID
Implements oist::ILayer.
Definition at line 248 of file LayerPvrnnBeta.cpp.
References oist::ContextPvrnnBeta::t_dp, oist::ContextPvrnnBeta::t_dq, and oist::ContextPvrnnBeta::t_kld.
load()
void oist::LayerPvrnnBeta::load (string path) virtual
Load the layer's parameters
Parameters
path path Data full path
Implements oist::ILayer.
Definition at line 684 of file LayerPvrnnBeta.cpp.
References oist::Utils::getDelimiter(), oist::Utils::loadEigen(), and oist::Exception::what().
print()
void oist::LayerPvrnnBeta::print () virtual
Shows the network state in the standard output
Implements oist::ILayer.
Definition at line 591 of file LayerPvrnnBeta.cpp.
save()
void oist::LayerPvrnnBeta::save (string path) virtual
Save the layer's parameters
Parameters
path Destination full path
Implements oist::ILayer.
Definition at line 809 of file LayerPvrnnBeta.cpp.
References oist::Utils::getDelimiter(), oist::Utils::saveEigen(), and oist::Exception::what().
t_backward()
void oist::LayerPvrnnBeta::t_backward (int time, int pID) virtual
[Training mode] Computes the backward (BPTT algorithm) inference process
Parameters
time Current time step
pID Primitive ID
Implements oist::ILayer.
Definition at line 433 of file LayerPvrnnBeta.cpp.
References oist::ContextPvrnnBeta::dq_top, oist::ContextPvrnnBeta::g_dqloss, oist::ContextPvrnnBeta::g_h_next, oist::ContextPvrnnBeta::g_hq_top, NON_ZERO, oist::ContextPvrnnBeta::t_dp, and oist::ContextPvrnnBeta::t_dq.
t_forward()
void oist::LayerPvrnnBeta::t_forward (int time, int pID) virtual
[Training mode] Computes the forward inference process
Parameters
time Current time step
pID Primitive ID
Implements oist::ILayer.
Definition at line 346 of file LayerPvrnnBeta.cpp.
References oist::ContextPvrnnBeta::dp_top, oist::ContextPvrnnBeta::dq_top, oist::Utils::randN(), oist::ContextPvrnnBeta::t_dp, oist::ContextPvrnnBeta::t_dq, oist::ContextPvrnnBeta::t_kld, and oist::Utils::tanH().
t_generate()
void oist::LayerPvrnnBeta::t_generate (int time, int pID) virtual
[Training mode] Computes the generative process
Parameters
time Current time step
pID Primitive ID
Implements oist::ILayer.
Definition at line 290 of file LayerPvrnnBeta.cpp.
References oist::ContextPvrnnBeta::dp_top, oist::Utils::randN(), oist::ContextPvrnnBeta::t_dp, and oist::Utils::tanH().
t_initBackward()
void oist::LayerPvrnnBeta::t_initBackward () virtual
[Training mode] Initializes the inference process backward computation
Implements oist::ILayer.
Definition at line 421 of file LayerPvrnnBeta.cpp.
References oist::ContextPvrnnBeta::g_h_next, oist::ContextPvrnnBeta::g_hq_top, and oist::Utils::zero().
Referenced by e_initBackward().
t_optAdam()
void oist::LayerPvrnnBeta::t_optAdam (int pID, float alpha, float beta1, float beta2) virtual
[Training mode] Computes ADAM optimization of parameters
Parameters
pID Primitive ID
alpha Adam optimization hyper parameter
beta1 Adam optimization hyper parameter
beta2 Adam optimization hyper parameter
Implements oist::ILayer.
Definition at line 531 of file LayerPvrnnBeta.cpp.
References oist::Utils::adam(), and oist::Utils::zero().
The documentation for this class was generated from the following files:
src/layer/LayerPvrnnBeta.h
src/layer/LayerPvrnnBeta.cpp