OIST-CNRU:NRL: oist::NetworkPvrnn Class Reference
oist::NetworkPvrnn Class Reference
#include <NetworkPvrnn.h>
Public Member Functions
NetworkPvrnn (map< string, float1DContainer > &paramMap, Dataset *dataset)
~NetworkPvrnn ()
int getNLayers ()
int getStateDim ()
void load (string)
void save (string)
void print ()
void t_generate (int, int, vectorXf2DContainer &)
void t_forward (int, int, vectorXf2DContainer &)
void t_backward (int, vectorXf2DContainer &, vectorXf3DContainer &, float &, float &, float &)
void t_optAdam (int, float, float, float)
float getRecError (vectorXf2DContainer &, vectorXf3DContainer &)
void a_predict (int, float *, string)
void a_feedForwardOutputFromContext (float *, float *)
void e_enable (int, int, float *, int, bool, bool)
void e_generate (float *)
bool e_initForward ()
void e_forward (vectorXf2DContainer &)
void e_backward (vectorXf2DContainer &, vectorXf2DContainer &, float &, float &, float &)
void e_copyParam ()
void e_overwriteParam ()
void e_optAdam (int, float, float, float)
void e_getState (float *)
void e_save (string)
Public Member Functions inherited from oist::INetwork
virtual ~INetwork ()
Detailed Description
This class implements a network type PV-RNN
Definition at line 66 of file NetworkPvrnn.h.
Constructor & Destructor Documentation
NetworkPvrnn()
oist::NetworkPvrnn::NetworkPvrnn (map< string, float1DContainer > & paramMap, Dataset * dataset)
Constructor
Parameters
paramMap Input map with layer information containers (number of d and z units, time constants, and the meta-parameters W)
dataset Pointer to a data-set object
Definition at line 55 of file NetworkPvrnn.cpp.
References oist::ILayer::getContext(), oist::Utils::getInstance(), oist::Dataset::getNPrim(), oist::Dataset::getNunitsPerDim(), oist::Dataset::getPrimLength(), oist::ILayer::getStateDim(), and oist::Utils::kaiming_uniform_initialization().
~NetworkPvrnn()
oist::NetworkPvrnn::~NetworkPvrnn ()
Definition at line 884 of file NetworkPvrnn.cpp.
Member Function Documentation
a_feedForwardOutputFromContext()
void oist::NetworkPvrnn::a_feedForwardOutputFromContext (float * input, float * output) virtual
[Analysis mode] Computes the output from feed-forwarding a given context. This method does not modify the internal state of the network, (i.e. the generative and inference processes are not involved). It only computes the output layer from a given context.
Parameters
input Input array with latent state for the involved layers concatenated
output Output container
Implements oist::INetwork.
Definition at line 781 of file NetworkPvrnn.cpp.
References oist::Dataset::decodeSoftmax(), and oist::Utils::softmax().
a_predict()
void oist::NetworkPvrnn::a_predict (int n, float * input, string path) virtual
[Analysis mode] Computes the generative process off-line and stores on disk
Parameters
n Number of generations
input Input array with initial state for all the layers concatenated
path Full path directory to save the output
Implements oist::INetwork.
Definition at line 797 of file NetworkPvrnn.cpp.
References oist::Dataset::decodeSoftmax(), oist::ContextPvrnn::dp_bottom_prev, oist::ContextPvrnn::dp_gen, oist::ContextPvrnn::dp_top_prev, oist::ILayer::getContext(), oist::Utils::saveContainer(), and oist::Utils::softmax().
e_backward()
void oist::NetworkPvrnn::e_backward (vectorXf2DContainer & X, vectorXf2DContainer & Y, float & rec, float & reg, float & loss) virtual
[Experiment mode] Back propagation through time computation (inference)
Parameters
X Input container with network generation from the posterior distribution e_forward
Y Input container with the reference data
rec Output reconstruction error
reg Output regulation error
loss Output loss function
Implements oist::INetwork.
Definition at line 684 of file NetworkPvrnn.cpp.
References oist::ILayer::e_backward(), oist::ILayer::e_initBackward(), oist::ContextPvrnn::e_kld, oist::ContextPvrnn::g_dqloss, oist::ContextPvrnn::g_h_next, oist::ContextPvrnn::g_hq_bottom_next, oist::ContextPvrnn::g_hq_top_next, oist::ILayer::getContext(), and NON_ZERO.
e_copyParam()
void oist::NetworkPvrnn::e_copyParam () virtual
[Experiment mode] Copies the network's parameters. It is used for greedy optimization
Implements oist::INetwork.
Definition at line 751 of file NetworkPvrnn.cpp.
e_enable()
void oist::NetworkPvrnn::e_enable (int pID, int winSize, float * param, int nT, bool store_gen, bool store_inf) virtual
[Experiment mode] Enables the experiment mode
Parameters
pID Primitive ID
winSize Sliding window size
param container with parameters
nT Number of experiment times
store_gen A flag indicating to store the generative process states. This should be used with caution, since memory allocation for large data may degrade performance. It is recommended to use e_getState to get the current state of the network, without storing information on the back-end side. Hence, the client front-end does the storage.
store_inf A flag indicating to store the inference process states. Valuable only if the parameter store_gen is set true. Thus should be used only for debugging, since memory allocation for large data may degrade performance. All the computation steps for the back propagation trough time (BPPT) algorithm are stored.
Implements oist::INetwork.
Definition at line 575 of file NetworkPvrnn.cpp.
e_forward()
void oist::NetworkPvrnn::e_forward (vectorXf2DContainer & output) virtual
[Experiment mode] Generation from the posterior distribution
Parameters
output Container for output recording
Implements oist::INetwork.
Definition at line 638 of file NetworkPvrnn.cpp.
References oist::ContextPvrnn::dp_bottom_prev, oist::ContextPvrnn::dp_top_prev, oist::ContextPvrnn::dq_bottom_prev, oist::ContextPvrnn::dq_top_prev, oist::ContextPvrnn::e_dp, oist::ContextPvrnn::e_dq, oist::ILayer::e_forward(), oist::ILayer::getContext(), and oist::Utils::softmax().
e_generate()
void oist::NetworkPvrnn::e_generate (float * output) virtual
[Experiment mode] Generation from the prior distribution
Parameters
output Container for output recording
Implements oist::INetwork.
Definition at line 604 of file NetworkPvrnn.cpp.
References oist::Dataset::decodeSoftmax(), oist::ContextPvrnn::dp_bottom_prev, oist::ContextPvrnn::dp_gen, oist::ContextPvrnn::dp_top_prev, oist::ILayer::e_generate(), oist::ILayer::getContext(), and oist::Utils::softmax().
e_getState()
void oist::NetworkPvrnn::e_getState (float * output) virtual
[Experiment mode] Writes the current network state to a float array. Both the generation and inference latent states are provided real time for analysis.
Parameters
output Float array reference. The size of the array can be obtained from getStateDim
Implements oist::INetwork.
Definition at line 772 of file NetworkPvrnn.cpp.
e_initForward()
bool oist::NetworkPvrnn::e_initForward () virtual
[Experiment mode] Initialize the inference process forward computations in experiment mode
Returns
A flag indicating the success of the operation
Implements oist::INetwork.
Definition at line 591 of file NetworkPvrnn.cpp.
e_optAdam()
void oist::NetworkPvrnn::e_optAdam (int pID, float alpha, float beta1, float beta2) virtual
[Experiment mode] Computes ADAM optimization of parameters
Parameters
pID Primitive ID
alpha Adam optimization hyper parameter
beta1 Adam optimization hyper parameter
beta2 Adam optimization hyper parameter
Implements oist::INetwork.
Definition at line 764 of file NetworkPvrnn.cpp.
e_overwriteParam()
void oist::NetworkPvrnn::e_overwriteParam () virtual
[Experiment mode] Overrides the network's parameters. It is used for greedy optimization
Implements oist::INetwork.
Definition at line 757 of file NetworkPvrnn.cpp.
e_save()
void oist::NetworkPvrnn::e_save (string path) virtual
[Experiment mode] Save the network model
Parameters
path Output directory full path
Implements oist::INetwork.
Definition at line 864 of file NetworkPvrnn.cpp.
getNLayers()
int oist::NetworkPvrnn::getNLayers () virtual
Get the number of layers
Returns
An integer representing the number of layers
Implements oist::INetwork.
Definition at line 156 of file NetworkPvrnn.cpp.
getRecError()
float oist::NetworkPvrnn::getRecError (vectorXf2DContainer & gen, vectorXf3DContainer & ref) virtual
Get the reconstruction error
Parameters
gen Container with the output generation by network
ref Container with the reference data
Returns
A real value for the reconstruction error
Implements oist::INetwork.
Definition at line 360 of file NetworkPvrnn.cpp.
References NON_ZERO.
getStateDim()
int oist::NetworkPvrnn::getStateDim () virtual
Gets the dimension of the network state space
Returns
An integer representing the dimension
Implements oist::INetwork.
Definition at line 161 of file NetworkPvrnn.cpp.
load()
void oist::NetworkPvrnn::load (string path) virtual
Load the network model
Parameters
path Model directory full path
Implements oist::INetwork.
Definition at line 425 of file NetworkPvrnn.cpp.
References oist::Utils::getDelimiter(), and oist::Utils::loadEigen().
print()
void oist::NetworkPvrnn::print ()
Definition at line 386 of file NetworkPvrnn.cpp.
save()
void oist::NetworkPvrnn::save (string path) virtual
Save the network model
Parameters
path Model directory full path
Implements oist::INetwork.
Definition at line 494 of file NetworkPvrnn.cpp.
References oist::Utils::getDelimiter(), and oist::Utils::saveEigen().
t_backward()
void oist::NetworkPvrnn::t_backward (int epoch, vectorXf2DContainer & X, vectorXf3DContainer & Y, float & rec, float & reg, float & loss) virtual
[Training mode] Back propagation through time computation (inference)
Parameters
epoch current epoch number
X Input container with network generation from the posterior distribution t_forward
Y Input container with the reference data
rec Output reconstruction error
reg Output regulation error
loss Output loss function
Implements oist::INetwork.
Definition at line 255 of file NetworkPvrnn.cpp.
References oist::ContextPvrnn::dq_bottom_prev, oist::ContextPvrnn::dq_top_prev, oist::ContextPvrnn::g_dqloss, oist::ContextPvrnn::g_h_next, oist::ContextPvrnn::g_hq_bottom_next, oist::ContextPvrnn::g_hq_top_next, oist::ILayer::getContext(), NON_ZERO, oist::ILayer::t_backward(), oist::ContextPvrnn::t_dq, and oist::ContextPvrnn::t_kld.
t_forward()
void oist::NetworkPvrnn::t_forward (int n, int pID, vectorXf2DContainer & output) virtual
[Training mode] Generation from the posterior distribution
Parameters
n number of time steps
pID Primitive ID
output Container for output recording
Implements oist::INetwork.
Definition at line 207 of file NetworkPvrnn.cpp.
References oist::ContextPvrnn::dp_bottom_prev, oist::ContextPvrnn::dp_top_prev, oist::ContextPvrnn::dq_bottom_prev, oist::ContextPvrnn::dq_top_prev, oist::ILayer::getContext(), oist::Utils::softmax(), oist::ContextPvrnn::t_dp, oist::ContextPvrnn::t_dq, and oist::ILayer::t_forward().
t_generate()
void oist::NetworkPvrnn::t_generate (int n, int pID, vectorXf2DContainer & output) virtual
[Training mode] Generation from the prior distribution
Parameters
n number of time steps
pID Primitive ID
output Container for output recording
Implements oist::INetwork.
Definition at line 167 of file NetworkPvrnn.cpp.
References oist::ContextPvrnn::dp_bottom_prev, oist::ContextPvrnn::dp_top_prev, oist::ILayer::getContext(), oist::Utils::softmax(), oist::ContextPvrnn::t_dp, and oist::ILayer::t_generate().
t_optAdam()
void oist::NetworkPvrnn::t_optAdam (int pID, float alpha, float beta1, float beta2) virtual
[Training mode] Computes ADAM optimization of parameters
Parameters
pID Primitive ID
alpha Adam optimization hyper parameter
beta1 Adam optimization hyper parameter
beta2 Adam optimization hyper parameter
Implements oist::INetwork.
Definition at line 337 of file NetworkPvrnn.cpp.
References oist::Utils::adam(), and oist::Utils::zero().
The documentation for this class was generated from the following files:
src/network/NetworkPvrnn.h
src/network/NetworkPvrnn.cpp