OIST-CNRU:NRL: oist::Exception Class Reference
oist::Exception Class Reference
#include <Exception.h>
Public Member Functions
Exception (string msg)
virtual const char * what () const throw ()
virtual ~Exception ()
Detailed Description
This class implements oist namespace Exception type
Definition at line 62 of file Exception.h.
Constructor & Destructor Documentation
Exception()
oist::Exception::Exception (string msg)
Constructor
Parameters
msg Message string
Definition at line 54 of file Exception.cpp.
~Exception()
oist::Exception::~Exception () virtual
Destructor
Definition at line 60 of file Exception.cpp.
Member Function Documentation
what()
const char * oist::Exception::what () const throw () virtual
Gets the exception message string
Definition at line 64 of file Exception.cpp.
Referenced by oist::LibNRL::load(), oist::LayerPvrnnBeta::load(), oist::LayerPvrnn::load(), oist::LibNRL::newModel(), oist::LayerPvrnnBeta::save(), oist::LayerPvrnn::save(), oist::LibNRL::t_background(), and oist::LibNRL::t_init().
The documentation for this class was generated from the following files:
src/utils/Exception.h
src/utils/Exception.cpp