OIST-CNRU:NRL: oist::ILayer Class Reference
oist::ILayer Class Reference abstract
#include <ILayer.h>
Public Member Functions
virtual int getStateDim ()=0
virtual void load (string path)=0
virtual void save (string path)=0
virtual void initContext (int pID)=0
virtual IContext * getContext ()=0
virtual void t_generate (int time, int pID)=0
virtual void t_forward (int time, int pID)=0
virtual void t_initBackward ()=0
virtual void t_backward (int time, int pID)=0
virtual void t_optAdam (int pID, float alpha, float beta1, float beta2)=0
virtual void a_init (float *)=0
virtual void a_predict ()=0
virtual void a_save (string path)=0
virtual void e_enable (int pID, int winSize, float param, int nT, bool store_gen, bool store_inf)=0
virtual void e_generate ()=0
virtual void e_initForward ()=0
virtual void e_forward ()=0
virtual void e_initBackward ()=0
virtual void e_backward (int time)=0
virtual void e_copyParam ()=0
virtual void e_overwriteParam ()=0
virtual void e_optAdam (int pID, float alpha, float beta1, float beta2)=0
virtual float * e_getState (float *output)=0
virtual void e_save (string path)=0
virtual void print ()=0
virtual ~ILayer ()
Detailed Description
Abstract class (Interface) for layer implementations
Definition at line 60 of file ILayer.h.
Constructor & Destructor Documentation
~ILayer()
virtual oist::ILayer::~ILayer () inline virtual
Virtual destructor
Definition at line 240 of file ILayer.h.
Member Function Documentation
a_init()
virtual void oist::ILayer::a_init (float *) pure virtual
[Analysis mode] Initialize off-line predictions
Parameters
Input state at time t=0
Implemented in oist::LayerPvrnn, and oist::LayerPvrnnBeta.
a_predict()
virtual void oist::ILayer::a_predict () pure virtual
[Analysis mode] Computes the generative process off-line
Implemented in oist::LayerPvrnn, and oist::LayerPvrnnBeta.
a_save()
virtual void oist::ILayer::a_save (string path) pure virtual
[Analysis mode] Save off-line computations to disk
Parameters
path Directory full path
Implemented in oist::LayerPvrnn, and oist::LayerPvrnnBeta.
e_backward()
virtual void oist::ILayer::e_backward (int time) pure virtual
[Experiment mode] Computes the backward pass of the BPTT algorithm for performing inference
Parameters
time Current time step
Implemented in oist::LayerPvrnn, and oist::LayerPvrnnBeta.
Referenced by oist::NetworkPvrnn::e_backward(), and oist::NetworkPvrnnBeta::e_backward().
e_copyParam()
virtual void oist::ILayer::e_copyParam () pure virtual
[Experiment model] Copies the parameters with optimal loss function (greedy optimization)
Implemented in oist::LayerPvrnn, and oist::LayerPvrnnBeta.
e_enable()
virtual void oist::ILayer::e_enable (int pID, int winSize, float param, int nT, bool store_gen, bool store_inf) pure virtual
[Experiment mode] Enables the experiment mode
Parameters
pID Primitive ID
winSize Sliding window size
param Input container with parameters
nT Number of experiment times
store_gen A flag indicating to store the generative process states. This should be used with caution, since memory allocation for large data may degrade performance. It is recommended to use e_getState to get the current state of the network, without storing information on the back-end side. Hence, the client front-end does the storage.
store_inf A flag indicating to store the inference process states. Valuable only if the parameter store_gen is set true. Thus should be used only for debugging, since memory allocation for large data may degrade performance. All the computation steps for the back propagation trough time (BPPT) algorithm are stored.
Implemented in oist::LayerPvrnn, and oist::LayerPvrnnBeta.
e_forward()
virtual void oist::ILayer::e_forward () pure virtual
[Experiment mode] Computes forward inference process
Implemented in oist::LayerPvrnn, and oist::LayerPvrnnBeta.
Referenced by oist::NetworkPvrnn::e_forward(), and oist::NetworkPvrnnBeta::e_forward().
e_generate()
virtual void oist::ILayer::e_generate () pure virtual
[Experiment mode] Computes one prediction with the generative process
Implemented in oist::LayerPvrnn, and oist::LayerPvrnnBeta.
Referenced by oist::NetworkPvrnn::e_generate(), and oist::NetworkPvrnnBeta::e_generate().
e_getState()
virtual float* oist::ILayer::e_getState (float * output) pure virtual
[Experiment mode] Writes the current layer state to a float array. Both the generation and inference latent states are provided real time for analysis.
Parameters
output Float array reference. The size of the array can be obtained from getStateDim
Returns
Pointer to the next writable position in the float array
Implemented in oist::LayerPvrnn, and oist::LayerPvrnnBeta.
e_initBackward()
virtual void oist::ILayer::e_initBackward () pure virtual
[Experiment mode] Initializes the backward inference process computation
Implemented in oist::LayerPvrnn, and oist::LayerPvrnnBeta.
Referenced by oist::NetworkPvrnn::e_backward(), and oist::NetworkPvrnnBeta::e_backward().
e_initForward()
virtual void oist::ILayer::e_initForward () pure virtual
[Experiment mode] Initialize the inference process forward computations
Implemented in oist::LayerPvrnn, and oist::LayerPvrnnBeta.
e_optAdam()
virtual void oist::ILayer::e_optAdam (int pID, float alpha, float beta1, float beta2) pure virtual
[Experiment mode] Computes ADAM optimization of parameters
Parameters
pID Primitive ID
alpha Adam optimization hyper parameter
beta1 Adam optimization hyper parameter
beta2 Adam optimization hyper parameter
Implemented in oist::LayerPvrnn, and oist::LayerPvrnnBeta.
e_overwriteParam()
virtual void oist::ILayer::e_overwriteParam () pure virtual
[Experiment model] Persists the parameters with optimal loss function (greedy optimization)
Implemented in oist::LayerPvrnn, and oist::LayerPvrnnBeta.
e_save()
virtual void oist::ILayer::e_save (string path) pure virtual
[Experiment mode] Save the network model
Parameters
path Output directory full path
Implemented in oist::LayerPvrnn, and oist::LayerPvrnnBeta.
getContext()
virtual IContext* oist::ILayer::getContext () pure virtual
Gets the layer context
Implemented in oist::LayerPvrnn, and oist::LayerPvrnnBeta.
Referenced by oist::NetworkPvrnn::a_predict(), oist::NetworkPvrnnBeta::a_predict(), oist::NetworkPvrnn::e_backward(), oist::NetworkPvrnnBeta::e_backward(), oist::NetworkPvrnn::e_forward(), oist::NetworkPvrnnBeta::e_forward(), oist::NetworkPvrnn::e_generate(), oist::NetworkPvrnnBeta::e_generate(), oist::NetworkPvrnn::NetworkPvrnn(), oist::NetworkPvrnnBeta::NetworkPvrnnBeta(), oist::NetworkPvrnn::t_backward(), oist::NetworkPvrnnBeta::t_backward(), oist::NetworkPvrnn::t_forward(), oist::NetworkPvrnnBeta::t_forward(), oist::NetworkPvrnn::t_generate(), and oist::NetworkPvrnnBeta::t_generate().
getStateDim()
virtual int oist::ILayer::getStateDim () pure virtual
Gets the dimension of the layer state space
Returns
dimension
Implemented in oist::LayerPvrnn, and oist::LayerPvrnnBeta.
Referenced by oist::NetworkPvrnn::NetworkPvrnn(), and oist::NetworkPvrnnBeta::NetworkPvrnnBeta().
initContext()
virtual void oist::ILayer::initContext (int pID) pure virtual
Initialized the layer context
Parameters
pID Primitive ID
Implemented in oist::LayerPvrnn, and oist::LayerPvrnnBeta.
load()
virtual void oist::ILayer::load (string path) pure virtual
Load the layer's parameters
Parameters
path path Data full path
Implemented in oist::LayerPvrnn, and oist::LayerPvrnnBeta.
print()
virtual void oist::ILayer::print () pure virtual
Shows the network state in the standard output
Implemented in oist::LayerPvrnn, and oist::LayerPvrnnBeta.
save()
virtual void oist::ILayer::save (string path) pure virtual
Save the layer's parameters
Parameters
path Destination full path
Implemented in oist::LayerPvrnn, and oist::LayerPvrnnBeta.
t_backward()
virtual void oist::ILayer::t_backward (int time, int pID) pure virtual
[Training mode] Computes the backward (BPTT algorithm) inference process
Parameters
time Current time step
pID Primitive ID
Implemented in oist::LayerPvrnn, and oist::LayerPvrnnBeta.
Referenced by oist::NetworkPvrnn::t_backward(), and oist::NetworkPvrnnBeta::t_backward().
t_forward()
virtual void oist::ILayer::t_forward (int time, int pID) pure virtual
[Training mode] Computes the forward inference process
Parameters
time Current time step
pID Primitive ID
Implemented in oist::LayerPvrnn, and oist::LayerPvrnnBeta.
Referenced by oist::NetworkPvrnn::t_forward(), and oist::NetworkPvrnnBeta::t_forward().
t_generate()
virtual void oist::ILayer::t_generate (int time, int pID) pure virtual
[Training mode] Computes the generative process
Parameters
time Current time step
pID Primitive ID
Implemented in oist::LayerPvrnn, and oist::LayerPvrnnBeta.
Referenced by oist::NetworkPvrnn::t_generate(), and oist::NetworkPvrnnBeta::t_generate().
t_initBackward()
virtual void oist::ILayer::t_initBackward () pure virtual
[Training mode] Initializes the inference process backward computation
Implemented in oist::LayerPvrnn, and oist::LayerPvrnnBeta.
t_optAdam()
virtual void oist::ILayer::t_optAdam (int pID, float alpha, float beta1, float beta2) pure virtual
[Training mode] Computes ADAM optimization of parameters
Parameters
pID Primitive ID
alpha Adam optimization hyper parameter
beta1 Adam optimization hyper parameter
beta2 Adam optimization hyper parameter
Implemented in oist::LayerPvrnn, and oist::LayerPvrnnBeta.
The documentation for this class was generated from the following file:
src/layer/ILayer.h