OIST-CNRU:NRL: oist::Dataset Class Reference
oist::Dataset Class Reference
#include <Dataset.h>
Public Member Functions
Dataset (string path, string prefix, int1DContainer &samples, float dsoft, float sigma, Utils *ut, IRobot *robot)
void encodeSoftmax (vectorXf4DContainer &output)
void encodeSoftmax (float *input, int *size, vectorXf2DContainer &output)
float decodeSoftmax (ArrayXf &input, int dim)
void getNunitsPerDim (int1DContainer &output)
int getPrimLength ()
int getNPrim ()
virtual ~Dataset ()
Detailed Description
This class provides the functionalities for encoding and decoding robot and network data
Definition at line 61 of file Dataset.h.
Constructor & Destructor Documentation
Dataset()
oist::Dataset::Dataset (string path, string prefix, int1DContainer & samples, float dsoft, float sigma, Utils * ut, IRobot * robot)
Constructor
Parameters
path Full path to the dataset
prefix Primitive filename prefix
samples Integer container with number of sample per primitives
dsoft The desired encoding range in the joint space for a neuron. That is, for a revolute joint, if dsoft=10 one neuron unit would encode 10 degrees.
sigma Parameter for the activation of the output unit, related to the dimension of the joint space, such that
where is the observation in the joint space, is the reference value, and the softmax normalization term is
ut Pointer to a Utils instance
robot Pointer to a IRobot extended instance
Definition at line 53 of file Dataset.cpp.
References oist::IRobot::getDOF(), oist::IRobot::getJointHighLimit(), oist::IRobot::getJointLowLimit(), and oist::IRobot::getJointRange().
~Dataset()
oist::Dataset::~Dataset () virtual
Definition at line 258 of file Dataset.cpp.
Member Function Documentation
decodeSoftmax()
float oist::Dataset::decodeSoftmax (ArrayXf & input, int dim) inline
Transforms back from softmax encoding of dimension j to a scalar value for the robot joint j
Parameters
input Input array with encoded data
dim Dimension of the joint space
Returns
Decoded value in the joint space
Definition at line 157 of file Dataset.h.
Referenced by oist::NetworkPvrnn::a_feedForwardOutputFromContext(), oist::NetworkPvrnnBeta::a_feedForwardOutputFromContext(), oist::NetworkPvrnn::a_predict(), oist::NetworkPvrnnBeta::a_predict(), oist::NetworkPvrnn::e_generate(), and oist::NetworkPvrnnBeta::e_generate().
encodeSoftmax() [1/2]
void oist::Dataset::encodeSoftmax (float * input, int * size, vectorXf2DContainer & output)
Computes softmax encoding
Parameters
input Pointer to the 1D input array data
size Pointer to an array containing the number time steps and the number of degrees of freedom in the input data
output Container to store encoded data
Definition at line 153 of file Dataset.cpp.
References NON_ZERO.
encodeSoftmax() [2/2]
void oist::Dataset::encodeSoftmax (vectorXf4DContainer & output)
Computes softmax encoding
Parameters
output Container to store encoded data
Definition at line 235 of file Dataset.cpp.
Referenced by oist::LibNRL::e_postdict(), and oist::LibNRL::newModel().
getNPrim()
int oist::Dataset::getNPrim ()
Gets the number of primitives in the data-set
Returns
number of primitives
Definition at line 141 of file Dataset.cpp.
Referenced by oist::NetworkPvrnn::NetworkPvrnn(), and oist::NetworkPvrnnBeta::NetworkPvrnnBeta().
getNunitsPerDim()
void oist::Dataset::getNunitsPerDim (int1DContainer & output)
Gets the number of neurons per dimension
Parameters
output Output dimension container
Definition at line 148 of file Dataset.cpp.
Referenced by oist::NetworkPvrnn::NetworkPvrnn(), and oist::NetworkPvrnnBeta::NetworkPvrnnBeta().
getPrimLength()
int oist::Dataset::getPrimLength ()
Gets the length of the sequences in the data-set, assumed to be of same length
Returns
primitive length
Definition at line 144 of file Dataset.cpp.
Referenced by oist::NetworkPvrnn::NetworkPvrnn(), oist::NetworkPvrnnBeta::NetworkPvrnnBeta(), and oist::LibNRL::newModel().
The documentation for this class was generated from the following files:
src/dataset/Dataset.h
src/dataset/Dataset.cpp