OIST-CNRU:NRL: oist::Utils Class Reference
oist::Utils Class Reference
#include <Utils.h>
Public Types
enum nonlinearity {
Linear =0, Conv, Sigmoid, Tanh,
ReLU, ReLU_Leaky
}
Public Member Functions
void ltrim (string &io, const string &chars)
void rtrim (string &io, const string &chars)
void trim (string &io, const string &chars)
void tolower (string &input)
void split (vector< string > &output, string input)
string getDelimiter ()
MatrixXf kaiming_uniform_initialization (int iDim, int oDim, nonlinearity type)
VectorXf kaiming_uniform_initialization (int dim)
void getProperties (map< string, float1DContainer > &mapFloat1D, map< string, string > &mapString, map< string, bool > &mapBool, string path)
template<typename T >
void power (T *io, float exp)
template<typename T >
void softmax (T *io)
template<typename T >
void randN (T *io)
template<typename T >
void shuffle (T *io)
template<typename T >
void zero (T *io)
template<typename T >
void tanH (T *io)
template<typename T >
void adam (T *p, T *g, T *m, T *v, int epoch, float alpha, float beta1, float beta2)
template<typename T >
void copyEigen (T *input, T *output)
template<typename T >
float * copyEigenData (T *eInput, float *fOutput)
template<typename T >
void saveEigen (ofstream *file, T *eInput, string delimiter)
template<typename T >
void saveScalar (ofstream *file, T input)
template<typename T >
void saveContainer (ofstream *file, T *input, string delimiter)
template<typename T >
void loadEigen (ifstream *file, T *output, string delimiter)
template<typename T >
void loadContainer (ifstream *file, T *output, string delimiter)
template<typename T >
void loadScalar (ifstream *file, T *output)
Static Public Member Functions
static Utils * getInstance ()
Detailed Description
This class provides functionality for string processing, data saving and loading. It implements a singleton design pattern
Definition at line 61 of file Utils.h.
Member Enumeration Documentation
nonlinearity
enum oist::Utils::nonlinearity
Enumerator
Linear
Conv
Sigmoid
Tanh
ReLU
ReLU_Leaky
Definition at line 73 of file Utils.h.
Member Function Documentation
adam()
template<typename T > void oist::Utils::adam (T * p, T * g, T * m, T * v, int epoch, float alpha, float beta1, float beta2) inline
Computes ADAM optimization
Parameters
p Input/Ouput parameter
g Input gradient
m Input m
v Input v
epoch Epoch number
alpha Adam optimization hyper parameter
beta1 Adam optimization hyper parameter
beta2 Adam optimization hyper parameter
Definition at line 306 of file Utils.h.
References NON_ZERO.
Referenced by oist::LayerPvrnnBeta::e_optAdam(), oist::LayerPvrnn::e_optAdam(), oist::NetworkPvrnn::t_optAdam(), oist::NetworkPvrnnBeta::t_optAdam(), oist::LayerPvrnnBeta::t_optAdam(), and oist::LayerPvrnn::t_optAdam().
copyEigen()
template<typename T > void oist::Utils::copyEigen (T * input, T * output) inline
Copy values from two Eigen objects
Parameters
input Input data
output Output data
Definition at line 321 of file Utils.h.
copyEigenData()
template<typename T > float * oist::Utils::copyEigenData (T * eInput, float * fOutput)
Copies Eigen data to a float array
Parameters
eInput Eigen data pointer
fOutput Float array pointer
Returns
pointer to the buffer next position
Definition at line 338 of file Utils.h.
Referenced by oist::LayerPvrnnBeta::e_getState(), and oist::LayerPvrnn::e_getState().
getDelimiter()
string oist::Utils::getDelimiter ()
Gets the file delimiter string to read/write data
Definition at line 206 of file Utils.cpp.
Referenced by oist::LayerPvrnnBeta::a_save(), oist::LayerPvrnn::a_save(), oist::LayerPvrnnBeta::e_save(), oist::LayerPvrnn::e_save(), oist::NetworkPvrnn::load(), oist::NetworkPvrnnBeta::load(), oist::LayerPvrnnBeta::load(), oist::LayerPvrnn::load(), oist::LibNRL::newModel(), oist::NetworkPvrnn::save(), oist::NetworkPvrnnBeta::save(), oist::LayerPvrnnBeta::save(), oist::LayerPvrnn::save(), oist::LibNRL::t_background(), oist::LibNRL::t_init(), and oist::LibNRL::t_loop().
getInstance()
Utils * oist::Utils::getInstance () static
Gets the singleton instance
Definition at line 65 of file Utils.cpp.
Referenced by oist::LayerPvrnn::LayerPvrnn(), oist::LayerPvrnnBeta::LayerPvrnnBeta(), oist::NetworkPvrnn::NetworkPvrnn(), and oist::NetworkPvrnnBeta::NetworkPvrnnBeta().
getProperties()
void oist::Utils::getProperties (map< string, float1DContainer > & mapFloat1D, map< string, string > & mapString, map< string, bool > & mapBool, string path)
Loads the property file
Parameters
mapFloat1D Output container for float1D map parameters
mapString Output container for string map parameters
mapBool Output container for bool map parameters
path Full path to the properties
Definition at line 104 of file Utils.cpp.
References tolower(), and trim().
Referenced by oist::LibNRL::newModel().
kaiming_uniform_initialization() [1/2]
VectorXf oist::Utils::kaiming_uniform_initialization (int dim)
kaiming_uniform initialization for biases
Parameters
dim Bias vector dimension
Definition at line 234 of file Utils.cpp.
kaiming_uniform_initialization() [2/2]
MatrixXf oist::Utils::kaiming_uniform_initialization (int iDim, int oDim, nonlinearity type)
kaiming_uniform initialization for weight matrices
Parameters
iDim Input space dimension
oDim Output space dimension
type Type of non-linearity
Definition at line 211 of file Utils.cpp.
Referenced by oist::LayerPvrnn::LayerPvrnn(), oist::LayerPvrnnBeta::LayerPvrnnBeta(), oist::NetworkPvrnn::NetworkPvrnn(), and oist::NetworkPvrnnBeta::NetworkPvrnnBeta().
loadContainer()
template<typename T > void oist::Utils::loadContainer (ifstream * file, T * output, string delimiter)
Loads container data from file
Parameters
file File object pointer
output Pointer to data collection
delimiter String delimiter
Definition at line 400 of file Utils.h.
Referenced by oist::LibNRL::newModel(), oist::LibNRL::t_background(), and oist::LibNRL::t_init().
loadEigen()
template<typename T > void oist::Utils::loadEigen (ifstream * file, T * output, string delimiter)
Loads Eigen data to from file
Parameters
file File object pointer
output Pointer to data collection
delimiter String delimiter
Definition at line 364 of file Utils.h.
Referenced by oist::NetworkPvrnn::load(), oist::NetworkPvrnnBeta::load(), oist::LayerPvrnnBeta::load(), and oist::LayerPvrnn::load().
loadScalar()
template<typename T > void oist::Utils::loadScalar (ifstream * file, T * output)
Loads a scalar from file
Parameters
file File object pointer
output Pointer to the scalar
Definition at line 435 of file Utils.h.
ltrim()
void oist::Utils::ltrim (string & io, const string & chars)
Trim chars from the left
Parameters
io Input/output string
chars Chars to be removed
Definition at line 82 of file Utils.cpp.
Referenced by trim().
power()
template<typename T > void oist::Utils::power (T * io, float exp) inline
Computes the power operation
Parameters
io Input element
exp Power exponent
Definition at line 261 of file Utils.h.
randN()
template<typename T > void oist::Utils::randN (T * io) inline
Computes Gaussian noise in N(1,0)
Parameters
io Input/Output data type
Definition at line 279 of file Utils.h.
Referenced by oist::LayerPvrnnBeta::a_predict(), oist::LayerPvrnn::a_predict(), oist::LayerPvrnnBeta::e_forward(), oist::LayerPvrnn::e_forward(), oist::LayerPvrnnBeta::e_generate(), oist::LayerPvrnn::e_generate(), oist::LayerPvrnnBeta::t_forward(), oist::LayerPvrnn::t_forward(), oist::LayerPvrnnBeta::t_generate(), and oist::LayerPvrnn::t_generate().
rtrim()
void oist::Utils::rtrim (string & io, const string & chars)
Trim chars from the right
Parameters
io Input/output string
chars Chars to be removed
Definition at line 87 of file Utils.cpp.
Referenced by trim().
saveContainer()
template<typename T > void oist::Utils::saveContainer (ofstream * file, T * input, string delimiter)
Saves a data container to file
Parameters
file File object pointer
input Pointer to data collection
delimiter String delimiter
Definition at line 355 of file Utils.h.
Referenced by oist::NetworkPvrnn::a_predict(), and oist::NetworkPvrnnBeta::a_predict().
saveEigen()
template<typename T > void oist::Utils::saveEigen (ofstream * file, T * eInput, string delimiter)
Saves Eigen data to file
Parameters
file File object pointer
eInput Eigen data
delimiter String delimiter
Definition at line 329 of file Utils.h.
Referenced by oist::LayerPvrnnBeta::a_save(), oist::LayerPvrnn::a_save(), oist::LayerPvrnnBeta::e_save(), oist::LayerPvrnn::e_save(), oist::NetworkPvrnn::save(), oist::NetworkPvrnnBeta::save(), oist::LayerPvrnnBeta::save(), and oist::LayerPvrnn::save().
saveScalar()
template<typename T > void oist::Utils::saveScalar (ofstream * file, T input)
Saves scalar data to file
Parameters
file File object pointer
input Scalar to be saved
Definition at line 347 of file Utils.h.
Referenced by oist::LayerPvrnnBeta::e_save(), and oist::LayerPvrnn::e_save().
shuffle()
template<typename T > void oist::Utils::shuffle (T * io) inline
Shuffles a container
Parameters
io Input/Output data type
Definition at line 286 of file Utils.h.
Referenced by oist::LibNRL::t_background(), and oist::LibNRL::t_loop().
softmax()
template<typename T > void oist::Utils::softmax (T * io) inline
Computes the softmax function
Parameters
io Input/Output data type
Definition at line 268 of file Utils.h.
Referenced by oist::NetworkPvrnn::a_feedForwardOutputFromContext(), oist::NetworkPvrnnBeta::a_feedForwardOutputFromContext(), oist::NetworkPvrnn::a_predict(), oist::NetworkPvrnnBeta::a_predict(), oist::NetworkPvrnn::e_forward(), oist::NetworkPvrnnBeta::e_forward(), oist::NetworkPvrnn::e_generate(), oist::NetworkPvrnnBeta::e_generate(), oist::NetworkPvrnn::t_forward(), oist::NetworkPvrnnBeta::t_forward(), oist::NetworkPvrnn::t_generate(), and oist::NetworkPvrnnBeta::t_generate().
split()
void oist::Utils::split (vector< string > & output, string input)
Splits a string and feed the tokens to a vector
Parameters
output Output vector
input Input text string
Definition at line 73 of file Utils.cpp.
tanH()
template<typename T > void oist::Utils::tanH (T * io) inline
Computes the hyperbolic tangent
Parameters
io Input/Output data type
Definition at line 299 of file Utils.h.
Referenced by oist::LayerPvrnnBeta::a_predict(), oist::LayerPvrnn::a_predict(), oist::LayerPvrnnBeta::e_forward(), oist::LayerPvrnn::e_forward(), oist::LayerPvrnnBeta::e_generate(), oist::LayerPvrnn::e_generate(), oist::LayerPvrnnBeta::t_forward(), oist::LayerPvrnn::t_forward(), oist::LayerPvrnnBeta::t_generate(), and oist::LayerPvrnn::t_generate().
tolower()
void oist::Utils::tolower (string & input)
Low caps a string
Parameters
input Input string
Definition at line 98 of file Utils.cpp.
Referenced by getProperties(), and main().
trim()
void oist::Utils::trim (string & io, const string & chars)
Trim chars from both sides
Parameters
io Input/output string
chars Chars to be removed
Definition at line 92 of file Utils.cpp.
References ltrim(), and rtrim().
Referenced by getProperties().
zero()
template<typename T > void oist::Utils::zero (T * io) inline
Sets the element to zero
Parameters
io Input/Output data type
Definition at line 291 of file Utils.h.
Referenced by oist::LayerPvrnnBeta::e_optAdam(), oist::LayerPvrnn::e_optAdam(), oist::LayerPvrnnBeta::e_overwriteParam(), oist::LayerPvrnn::e_overwriteParam(), oist::LayerPvrnnBeta::t_initBackward(), oist::LayerPvrnn::t_initBackward(), oist::NetworkPvrnn::t_optAdam(), oist::NetworkPvrnnBeta::t_optAdam(), oist::LayerPvrnnBeta::t_optAdam(), and oist::LayerPvrnn::t_optAdam().
The documentation for this class was generated from the following files:
src/utils/Utils.h
src/utils/Utils.cpp