OIST-CNRU:NRL: oist::CircularBuffer Class Reference
oist::CircularBuffer Class Reference
#include <CircularBuffer.h>
Public Member Functions
CircularBuffer (int size, int nDOF)
void push (float *input)
int size ()
float * getData ()
~CircularBuffer ()
Detailed Description
This class implements a circular buffer (queue)
Definition at line 57 of file CircularBuffer.h.
Constructor & Destructor Documentation
CircularBuffer()
oist::CircularBuffer::CircularBuffer (int size, int nDOF)
Constructor
Parameters
size Maximum buffer size
nDOF Number of degrees of freedom (the dimension of data to be queued)
Definition at line 101 of file CircularBuffer.h.
~CircularBuffer()
oist::CircularBuffer::~CircularBuffer ()
Destructor
Definition at line 151 of file CircularBuffer.h.
Member Function Documentation
getData()
float * oist::CircularBuffer::getData ()
Gets a pointer to the first element of data stored
Returns
Pointer to the first element on the data array
Definition at line 146 of file CircularBuffer.h.
Referenced by demonstrateExperiment().
push()
void oist::CircularBuffer::push (float * input)
Push data at the end of the buffer. Automatically dequeues if the buffer is full.
Parameters
input Input data array of
Definition at line 113 of file CircularBuffer.h.
Referenced by demonstrateExperiment().
size()
int oist::CircularBuffer::size ()
Gets the current size of the buffer
Definition at line 141 of file CircularBuffer.h.
Referenced by demonstrateExperiment().
The documentation for this class was generated from the following file:
src/standalone/CircularBuffer.h