OIST-CNRU:NRL: oist::IRobot Class Reference
oist::IRobot Class Reference abstract
#include <IRobot.h>
Public Member Functions
virtual int getDOF (void)=0
virtual void getJointLowLimit (float1DContainer &output)=0
virtual void getJointHighLimit (float1DContainer &output)=0
virtual void getJointRange (float1DContainer &output)=0
virtual ~IRobot ()
Detailed Description
Abstract class (Interface) for robot implementations
Definition at line 60 of file IRobot.h.
Constructor & Destructor Documentation
~IRobot()
virtual oist::IRobot::~IRobot () inline virtual
Destructor
Definition at line 91 of file IRobot.h.
Member Function Documentation
getDOF()
virtual int oist::IRobot::getDOF (void) pure virtual
Gets the number of degrees of freedom (DoF) of the robot
Returns
Integer number of DoF
Implemented in oist::Cartesian, oist::Generic, and oist::Torobo.
Referenced by oist::Dataset::Dataset(), and oist::LibNRL::newModel().
getJointHighLimit()
virtual void oist::IRobot::getJointHighLimit (float1DContainer & output) pure virtual
Gets the superior limit of the robot's joints
Parameters
output Output float vector container
Implemented in oist::Cartesian, oist::Generic, and oist::Torobo.
Referenced by oist::Dataset::Dataset().
getJointLowLimit()
virtual void oist::IRobot::getJointLowLimit (float1DContainer & output) pure virtual
Gets the inferior limit of the robot's joints
Parameters
output Output float vector container
Implemented in oist::Cartesian, oist::Generic, and oist::Torobo.
Referenced by oist::Dataset::Dataset().
getJointRange()
virtual void oist::IRobot::getJointRange (float1DContainer & output) pure virtual
Gets the interval range of the robot's joints
Parameters
output Output float vector container
Implemented in oist::Cartesian, oist::Generic, and oist::Torobo.
Referenced by oist::Dataset::Dataset().
The documentation for this class was generated from the following file:
src/robot/IRobot.h