Neural Robotics Library: main Namespace Reference
main Namespace Reference
Classes
class DemonstratePostdiction
class DemonstrateTraining
Variables
nrl = NRL()
string path = '';
argv = sys.argv
argc = len(argv)
arg_s = argv[i].lower()
Variable Documentation
arg_s
main.arg_s = argv[i].lower()
Definition at line 218 of file main.py.
Referenced by main().
argc
main.argc = len(argv)
Definition at line 208 of file main.py.
Referenced by main().
argv
main.argv = sys.argv
Definition at line 207 of file main.py.
Referenced by main().
nrl
main.nrl = NRL()
Definition at line 202 of file main.py.
Referenced by demonstrateExperiment(), demonstrateTraining(), and main().
path
main.path = '';
Definition at line 205 of file main.py.
Referenced by main(), and oist::Utils.Utils().