OIST-CNRU:NRL: src/lib/nrl.cpp File Reference
nrl.cpp File Reference
#include "LibNRL.h"
Functions
LibNRL * getInstance ()
void newModel (LibNRL *nrl, const char *path)
void load (LibNRL *nrl)
int getNDof (LibNRL *nrl)
int getNLayers (LibNRL *nrl)
int getStateDim (LibNRL *nrl)
void t_background (LibNRL *nrl)
void t_init (LibNRL *nrl, bool show)
void t_loop (LibNRL *nrl, float *output, int n)
void t_end (LibNRL *nrl)
void e_enable (LibNRL *nrl, int pID, int ws, float *param, int ne, int epoch, float alpha, float beta1, float beta2, bool store_s, bool store_p)
void e_postdict (LibNRL *nrl, float *input, float *output, bool show)
void e_generate (LibNRL *nrl, float *output)
void e_save (LibNRL *nrl, const char *path)
void e_getState (LibNRL *nrl, float *output)
void a_predict (LibNRL *nrl, const char *path, int n, float *input)
void a_getOutputFromContext (LibNRL *nrl, float *input, float *output)
Function Documentation
a_getOutputFromContext()
void a_getOutputFromContext (LibNRL * nrl, float * input, float * output)
Computes the output from feed-forwarding a given context. This method does not modify the internal state of the network, (i.e. the generative and inference processes are not involved). It only computes the output layer from a given context.
Parameters
nrl Pointer to a LibNRL instance
input Array with latent state, whose dimension can be obtained through 'getStateDim'
output Array container
Definition at line 260 of file nrl.cpp.
References oist::LibNRL::a_feedForwardOutputFromContext().
a_predict()
void a_predict (LibNRL * nrl, const char * path, int n, float * input)
Generative off-line n time steps predictions from the initial context provided and store computations on disk.
Parameters
nrl Pointer to a LibNRL instance
path Output full path dir
n Number of time steps
input Array with latent state, whose dimension can be obtained through 'getStateDim'
Definition at line 247 of file nrl.cpp.
References oist::LibNRL::a_predict().
e_enable()
void e_enable (LibNRL * nrl, int pID, int ws, float * param, int ne, int epoch, float alpha, float beta1, float beta2, bool store_s, bool store_p)
Enables on-line experiment mode
Parameters
nrl Pointer to a LibNRL instance
pID Primitive ID
ws Sliding window size
param Parameters array for the neural network model
ne Number of experiment time steps
epoch Number of post-diction epochs
alpha Adam optimization hyper parameter
beta1 Adam optimization hyper parameter
beta2 Adam optimization hyper parameter
store_s A flag indicating to store the states on disk (if true performance can be affected)
store_p A flag indicating to store intermediate BPPT computations (if true performance can be affected)
Definition at line 177 of file nrl.cpp.
References oist::LibNRL::e_enable().
e_generate()
void e_generate (LibNRL * nrl, float * output)
Generates output from the prior distribution
Parameters
nrl Pointer to a LibNRL instance
output Array for storing the robot joint positions
Definition at line 209 of file nrl.cpp.
References oist::LibNRL::e_generate().
e_getState()
void e_getState (LibNRL * nrl, float * output)
Gets the current state of the network and writes data to the output buffer. This method is recommended for saving data in experiments.
Parameters
nrl Pointer to a LibNRL instance
output Array with latent state, whose dimension can be obtained through getStateDim once the model has been loaded.
Definition at line 234 of file nrl.cpp.
References oist::LibNRL::e_getState().
e_postdict()
void e_postdict (LibNRL * nrl, float * input, float * output, bool show)
Computes the post-diction (inference) process
Parameters
nrl Pointer to a LibNRL instance
input Sliding window buffer array
output Array for loss function components (reconstruction error, regulation error, loss)
show A flag indicating to show log in the standard output
Definition at line 199 of file nrl.cpp.
References oist::LibNRL::e_postdict().
e_save()
void e_save (LibNRL * nrl, const char * path)
Stores the experimental data in disk in case this functionality was set in e_enable It is recommended saving data in background only for short-time experiments, since performance can be affected. Another way of storing information is through the method e_getState which do not buffer data history but provides only the current state. Hence, the client application is in charge of storing data locally.
Parameters
nrl Pointer to a LibNRL instance
path Output full path
Definition at line 223 of file nrl.cpp.
References oist::LibNRL::e_save().
getInstance()
LibNRL* getInstance ()
This file is only wraps the API of LibNRL for shared library compilation The documentation of these methods should be consulted in LibNRL.h Gets a singleton instance to a LibNRL object
Returns
A pointer to a LibNRL instance
Definition at line 66 of file nrl.cpp.
References oist::LibNRL::getInstance().
Referenced by main().
getNDof()
int getNDof (LibNRL * nrl)
Gets the number of degrees of freedom (DoF) of the network output
Parameters
nrl Pointer to a LibNRL instance
Returns
Number of DoF
Definition at line 93 of file nrl.cpp.
References oist::LibNRL::getNDof().
getNLayers()
int getNLayers (LibNRL * nrl)
Gets the number of intermediate layers
Parameters
nrl Pointer to a LibNRL instance
Returns
Number of layers
Definition at line 102 of file nrl.cpp.
References oist::LibNRL::getNLayers().
getStateDim()
int getStateDim (LibNRL * nrl)
Gets the dimension of the network state space
Parameters
nrl Pointer to a LibNRL instance
Returns
Dimension
Definition at line 111 of file nrl.cpp.
References oist::LibNRL::getStateDim().
load()
void load (LibNRL * nrl)
Loads the network model
Parameters
nrl Pointer to a LibNRL instance
Definition at line 84 of file nrl.cpp.
References oist::LibNRL::load().
newModel()
void newModel (LibNRL * nrl, const char * path)
Creates a new model
Parameters
nrl Pointer to a LibNRL instance
path Full path to the properties file
Definition at line 76 of file nrl.cpp.
References oist::LibNRL::newModel().
t_background()
void t_background (LibNRL * nrl)
Training in background mode. The training parameters are
Parameters
nrl Pointer to a LibNRL instance fully red from the properties file
Definition at line 122 of file nrl.cpp.
References oist::LibNRL::t_background().
t_end()
void t_end (LibNRL * nrl)
Ending of interactive training mode
Parameters
nrl Pointer to a LibNRL instance
Definition at line 157 of file nrl.cpp.
References oist::LibNRL::t_end().
t_init()
void t_init (LibNRL * nrl, bool show)
Initialization of interactive training mode
Parameters
nrl Pointer to a LibNRL instance
show Flag indicating to log training in the stdout
Definition at line 131 of file nrl.cpp.
References oist::LibNRL::t_init().
t_loop()
void t_loop (LibNRL * nrl, float * output, int n)
Loop iteration in interactive training mode
Parameters
nrl Pointer to a LibNRL instance
output Output array for the tuple (step, RE_Q, RE_P, REG, loss, opt)
Field Description
step Current training time step
RE_Q Reconstruction error from the posterior distribution
RE_P Reconstruction error from the prior distribution
REG Regulation error KL-Div(Prior,posterior)
loss Loss function error
opt Integer flag: (1) Global optimal loss, (0) otherwise
n Number of training epochs
Definition at line 149 of file nrl.cpp.
References oist::LibNRL::t_loop().